In [ ]:
sentence = "I like to eat pizza"


In [ ]:
U = [[0.4, -0.3, 0.1, -0.2, 0.5],
[0.1, -0.2, 0.3, 0.2, -0.4],
[0.2, -0.1, 0.5, 0.4, -0.3]]

V = [[0.2, 0.6, -0.1],
[0.3, -0.2, 0.4],
[-0.4, 0.1, 0.5],
[0.1, 0.2, 0.3]]

W = [[0.2, -0.1, 0.3],
[-0.1, 0.4, -0.2],
[0.4, -0.3, 0.5]]
h_0 = [0.1, -0.1, 0.2]





In [ ]:
import numpy as np
import pandas as pd
from sklearn.decomposition import TruncatedSVD

# Step 1: Prepare the sentence and tokenize it
sentence = "I like to eat pizza"
words = sentence.lower().split()  # Tokenize and convert to lowercase

# Step 2: Create a co-occurrence matrix
window_size = 1  # Define the window size (1 means immediate neighbors)
vocab = sorted(set(words))  # Create a vocabulary (unique words in the sentence)
word_to_idx = {word: idx for idx, word in enumerate(vocab)}  # Map each word to an index
co_occurrence_matrix = np.zeros((len(vocab), len(vocab)))  # Initialize a square matrix

# Fill in the co-occurrence matrix based on the context window
for i, word in enumerate(words):
    word_idx = word_to_idx[word]
    # Look at neighbors within the window size
    for j in range(i - window_size, i + window_size + 1):
        if j >= 0 and j < len(words) and i != j:
            neighbor_idx = word_to_idx[words[j]]
            co_occurrence_matrix[word_idx, neighbor_idx] += 1

# Step 3: Convert co-occurrence matrix to a DataFrame for better readability
co_occurrence_df = pd.DataFrame(co_occurrence_matrix, columns=vocab, index=vocab)
print("Co-occurrence Matrix:\n", co_occurrence_df)

svd = TruncatedSVD(n_components=5)
word_embeddings = svd.fit_transform(co_occurrence_matrix)


embeddings_df = pd.DataFrame(word_embeddings, columns=["Dim1", "Dim2", "Dim3", "Dim4", "Dim5"], index=vocab)
print("\nWord Embeddings (5D):\n", embeddings_df)

word_embeddings_truncated = word_embeddings[:3, :]
print("\nTruncated Word Embeddings (3x5):\n", word_embeddings_truncated)


Co-occurrence Matrix:
        eat    i  like  pizza   to
eat    0.0  0.0   0.0    1.0  1.0
i      0.0  0.0   1.0    0.0  0.0
like   0.0  1.0   0.0    0.0  1.0
pizza  1.0  0.0   0.0    0.0  0.0
to     1.0  0.0   1.0    0.0  0.0

Word Embeddings (5D):
                Dim1          Dim2          Dim3          Dim4          Dim5
eat   -2.220446e-16  1.224745e+00  7.071068e-01 -2.220446e-16  2.220446e-16
i      7.071068e-01  4.440892e-16 -3.330669e-16  7.071068e-01  1.110223e-16
like  -3.330669e-16  1.224745e+00 -7.071068e-01 -3.330669e-16  1.110223e-16
pizza  7.071068e-01  0.000000e+00  0.000000e+00 -7.071068e-01  0.000000e+00
to     1.414214e+00  4.440892e-16 -3.330669e-16  1.110223e-16  1.110223e-16

Truncated Word Embeddings (3x5):
 [[-2.22044605e-16  1.22474487e+00  7.07106781e-01 -2.22044605e-16
   2.22044605e-16]
 [ 7.07106781e-01  4.44089210e-16 -3.33066907e-16  7.07106781e-01
   1.11022302e-16]
 [-3.33066907e-16  1.22474487e+00 -7.07106781e-01 -3.33066907e-16
   1.11022302e-16]]


In [ ]:
embeddings_df.head()

Dim1          Dim2          Dim3          Dim4          Dim5
eat   -2.220446e-16  1.224745e+00  7.071068e-01 -2.220446e-16  2.220446e-16
i      7.071068e-01  4.440892e-16 -3.330669e-16  7.071068e-01  1.110223e-16
like  -3.330669e-16  1.224745e+00 -7.071068e-01 -3.330669e-16  1.110223e-16
pizza  7.071068e-01  0.000000e+00  0.000000e+00 -7.071068e-01  0.000000e+00
to     1.414214e+00  4.440892e-16 -3.330669e-16  1.110223e-16  1.110223e-16

In [ ]:
embed_i = embeddings_df.loc["i"].values


U = np.array([
    [0.4, -0.3, 0.1, -0.2, 0.5],
    [0.1, -0.2, 0.3, 0.2, -0.4],
    [0.2, -0.1, 0.5, 0.4, -0.3]
])
n
result = np.dot(U, embed_i)


print("Result of multiplying row 'i' with U:", result)

Result of multiplying row 'i' with U: [0.14142136 0.21213203 0.42426407]


In [ ]:
import numpy as np
import pandas as pd



word_embeddings = embeddings_df.values

U = np.array([
    [0.4, -0.3, 0.1, -0.2, 0.5],
    [0.1, -0.2, 0.3, 0.2, -0.4],
    [0.2, -0.1, 0.5, 0.4, -0.3]
])

result = np.dot(U, word_embeddings.T)


print("Result of U multiplied by word embeddings:\n", result)


Result of U multiplied by word embeddings:
 [[-0.29671278  0.14142136 -0.43813414  0.42426407  0.56568542]
 [-0.03281694  0.21213203 -0.45708101 -0.07071068  0.14142136]
 [ 0.2310789   0.42426407 -0.47602788 -0.14142136  0.28284271]]


In [ ]:

W = [[0.2, -0.1, 0.3],
[-0.1, 0.4, -0.2],
[0.4, -0.3, 0.5]]
h_0 = [0.1, -0.1, 0.2]

result2  = np.dot(W,h_0)

print(result2)

[ 0.09 -0.09  0.17]


In [ ]:
b=0
at = b + np.dot(W,h_0) + np.dot(U, embed_i)
print(at)

[0.23142136 0.12213203 0.59426407]


In [ ]:
ht_1 = np.tanh(at)
print(ht_1)

[0.22737666 0.12152839 0.53295544]


In [ ]:
V = [[0.2, 0.6, -0.1],
[0.3, -0.2, 0.4],
[-0.4, 0.1, 0.5],
[0.1, 0.2, 0.3]]
c = 1
outp_y = c + np.dot(V, ht_1)
print(outp_y)

[1.06509682 1.2570895  1.18767989 1.20692997]


In [ ]:
import numpy as np

def softmax(x):
    # Subtract the max value to prevent overflow during exponentiation
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0, keepdims=True)

yt_1 = softmax(outp_y)
print(yt_1)

[0.22249619 0.2695901  0.25151259 0.25640113]


In [ ]:
custom_order = ["i", "like", "to", "eat", "pizza"]

# Reorder the DataFrame rows based on the custom order
reordered_df = embeddings_df.loc[custom_order]
reordered_df

Dim1          Dim2          Dim3          Dim4          Dim5
i      7.071068e-01  4.440892e-16 -3.330669e-16  7.071068e-01  1.110223e-16
like  -3.330669e-16  1.224745e+00 -7.071068e-01 -3.330669e-16  1.110223e-16
to     1.414214e+00  4.440892e-16 -3.330669e-16  1.110223e-16  1.110223e-16
eat   -2.220446e-16  1.224745e+00  7.071068e-01 -2.220446e-16  2.220446e-16
pizza  7.071068e-01  0.000000e+00  0.000000e+00 -7.071068e-01  0.000000e+00

In [ ]:
import numpy as np
import pandas as pd


def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0, keepdims=True)

U = [[0.4, -0.3, 0.1, -0.2, 0.5],
[0.1, -0.2, 0.3, 0.2, -0.4],
[0.2, -0.1, 0.5, 0.4, -0.3]]

V = [[0.2, 0.6, -0.1],
[0.3, -0.2, 0.4],
[-0.4, 0.1, 0.5],
[0.1, 0.2, 0.3]]

W = [[0.2, -0.1, 0.3],
[-0.1, 0.4, -0.2],
[0.4, -0.3, 0.5]]
h_0 = [0.1, -0.1, 0.2]

outputs = []
hidden_states = []

for word in reordered_df.index:

    embed_i = embeddings_df.loc[word].values


    at = b + np.dot(W, h_0) + np.dot(U, embed_i)


    ht_1 = np.tanh(at)

    outp_y = c + np.dot(V, ht_1)


    yt_1 = softmax(outp_y)


    outputs.append((word, yt_1))
    hidden_states.append((word,ht_1))


    h_0 = ht_1


for word, output in hidden_states:
    print(f"Output for word '{word}': {output}")
for word, hidden_state in hidden_states:
    print(f"hiddenstate for word '{word}': {hidden_state}")

Output for word 'i': [0.22737666 0.12152839 0.53295544]
Output for word 'like': [-0.2401422  -0.49131964 -0.15382716]
Output for word 'to': [ 4.78194431e-01 -3.26845263e-04  2.51738563e-01]
Output for word 'eat': [-0.12486458 -0.13036863  0.49926304]
Output for word 'pizza': [ 0.50953901 -0.20718116  0.09706832]
hiddenstate for word 'i': [0.22737666 0.12152839 0.53295544]
hiddenstate for word 'like': [-0.2401422  -0.49131964 -0.15382716]
hiddenstate for word 'to': [ 4.78194431e-01 -3.26845263e-04  2.51738563e-01]
hiddenstate for word 'eat': [-0.12486458 -0.13036863  0.49926304]
hiddenstate for word 'pizza': [ 0.50953901 -0.20718116  0.09706832]


In [2]:
import numpy as np
from collections import defaultdict

# Sample Data
texts = ["I love this product", "This is terrible", "Awesome!", "Waste of money"]
labels = [1, 0, 1, 0]  # 1 for positive, 0 for negative

# Tokenization and Vocabulary Creation
vocab = defaultdict(lambda: len(vocab))
processed_texts = [[vocab[word.lower()] for word in sentence.split()] for sentence in texts]
vocab = dict(vocab)

# Padding
max_length = max(len(sentence) for sentence in processed_texts)
padded_texts = [sentence + [0] * (max_length - len(sentence)) for sentence in processed_texts]


embedding_dim = U.shape[1]
embeddings = np.random.rand(len(vocab), embedding_dim)

U = np.array([[0.4, -0.3, 0.1, -0.2, 0.5],
              [0.1, -0.2, 0.3, 0.2, -0.4],
              [0.2, -0.1, 0.5, 0.4, -0.3]])

V = np.array([[0.2, 0.6, -0.1],
              [0.3, -0.2, 0.4],
              [-0.4, 0.1, 0.5]])

W = np.array([[0.2, -0.1, 0.3],
              [-0.1, 0.4, -0.2],
              [0.4, -0.3, 0.5]])

b = np.zeros(3)
c = np.zeros(3)
h_0 = np.array([0.1, -0.1, 0.2])


def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0, keepdims=True)


outputs = []
hidden_states = []

for sentence in padded_texts:
    h_t = h_0
    for word_idx in sentence:
        embed_i = embeddings[word_idx]


        a_t = b + np.dot(W, h_t) + np.dot(U, embed_i)


        h_t = np.tanh(a_t)


        o_t = c + np.dot(V, h_t)
        y_t = softmax(o_t)


        word = list(vocab.keys())[list(vocab.values()).index(word_idx)]
        outputs.append((word, y_t))
        hidden_states.append((word, h_t))


print("Outputs:")
for word, output in outputs:
    print(f"Output for word '{word}': {output}")

print("\nHidden States:")
for word, hidden_state in hidden_states:
    print(f"Hidden state for word '{word}': {hidden_state}")


Outputs:
Output for word 'i': [0.28246845 0.36631097 0.35122057]
Output for word 'love': [0.27667491 0.4316826  0.29164249]
Output for word 'this': [0.24593455 0.44909149 0.30497397]
Output for word 'product': [0.24424608 0.44746266 0.30829126]
Output for word 'this': [0.28568431 0.40338305 0.31093265]
Output for word 'is': [0.26443443 0.42389517 0.3116704 ]
Output for word 'terrible': [0.2546947  0.44117908 0.30412621]
Output for word 'i': [0.24712113 0.42232427 0.3305546 ]
Output for word 'awesome!': [0.28271168 0.42259436 0.29469395]
Output for word 'i': [0.25796457 0.39996876 0.34206667]
Output for word 'i': [0.2584383  0.40560471 0.33595699]
Output for word 'i': [0.2568762  0.40863278 0.33449101]
Output for word 'waste': [0.2900924  0.38308356 0.32682404]
Output for word 'of': [0.26668811 0.41919482 0.31411707]
Output for word 'money': [0.23956811 0.47459143 0.28584046]
Output for word 'i': [0.23694589 0.42578973 0.33726438]

Hidden States:
Hidden state for word 'i': [0.18220012 0